---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: sampleapp
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: sampleapp
  namespace: tap-demo
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/nkdgc/sampleapp
  params:
    - name: pvSize
      value: 2G
    - name: volumes
      value:
        volumes:
        - name: data-mount
          persistentVolumeClaim:
            claimName: sampleapp-volumes
        volumeMounts:
         - name: data-mount
           mountPath: /data

